[tool.poetry]
name = "cpenv"
version = "0.5.0"
description = "Cross-platform module and environment management."
authors = ["Dan Bradham <danielbradham@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=2.7, >=3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
