[tool.poetry]
name = "cpenv"
version = "0.5.0"
description = "Cross-platform module and environment management."
authors = ["Dan Bradham <danielbradham@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^2.7 || ^3.6"

[tool.poetry.dev-dependencies]
nose = "^1.3.7"
coverage = "^5.1"
isort = "^4.3.21"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
