name: Test

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - 'main'
  pull_request:
    paths-ignore:
      - 'docs/**'

concurrency:
  group: tests-${{ github.head_ref || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  tests:
    name: ${{ matrix.os }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10']
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python ${{ matrix.python-version }}
        id: setup_python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
          cache-dependency-path: 'pyproject.toml'

      - name: Install dependencies
        run: |
          poetry env use ${{ steps.setup_python.outputs.python-path }}
          poetry install

      - name: Run tests
        run: poetry run python -m tasks test
